"""empty message

Revision ID: b3073b9c6f2a
Revises: b2d3d4ed7a08
Create Date: 2022-10-31 13:42:53.978715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3073b9c6f2a'
down_revision = 'b2d3d4ed7a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('num_of_moons', sa.Integer(), nullable=True))
    op.drop_column('planet', 'number_moons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('number_moons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'num_of_moons')
    # ### end Alembic commands ###
